<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_menus')->delete();
        
        \DB::table('admin_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'parent_id' => 0,
                'order' => 0,
                'title' => '主页',
                'icon' => 'mdi:chart-line',
                'url' => '/index',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            1 => 
            array (
                'id' => 2,
                'parent_id' => 0,
                'order' => 99,
                'title' => '设置',
                'icon' => 'material-symbols:settings-outline',
                'url' => '/setting',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            2 => 
            array (
                'id' => 3,
                'parent_id' => 87,
                'order' => 3,
                'title' => '管理员',
                'icon' => 'ph:user-gear',
                'url' => '/setting/admin/users',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            3 => 
            array (
                'id' => 4,
                'parent_id' => 87,
                'order' => 2,
                'title' => '角色',
                'icon' => 'carbon:user-role',
                'url' => '/setting/admin/roles',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            4 => 
            array (
                'id' => 5,
                'parent_id' => 87,
                'order' => 1,
                'title' => '权限',
                'icon' => 'fluent-mdl2:permissions',
                'url' => '/setting/admin/permissions',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            5 => 
            array (
                'id' => 6,
                'parent_id' => 87,
                'order' => 0,
                'title' => '菜单',
                'icon' => 'ant-design:menu-unfold-outlined',
                'url' => '/setting/admin/menus',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-05-11 23:26:37',
            ),
            6 => 
            array (
                'id' => 8,
                'parent_id' => 1,
                'order' => 0,
                'title' => '首页',
                'icon' => NULL,
                'url' => '/index/index',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:36:46',
                'updated_at' => '2023-05-11 23:26:47',
            ),
            7 => 
            array (
                'id' => 9,
                'parent_id' => 1,
                'order' => 1,
                'title' => '商品统计',
                'icon' => NULL,
                'url' => '/index/product',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:38:10',
                'updated_at' => '2023-05-11 23:26:56',
            ),
            8 => 
            array (
                'id' => 10,
                'parent_id' => 1,
                'order' => 2,
                'title' => '用户统计',
                'icon' => NULL,
                'url' => '/index/user',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:38:36',
                'updated_at' => '2023-05-11 23:27:04',
            ),
            9 => 
            array (
                'id' => 11,
                'parent_id' => 1,
                'order' => 3,
                'title' => '交易统计',
                'icon' => NULL,
                'url' => '/index/trade',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:39:15',
                'updated_at' => '2023-05-11 23:27:22',
            ),
            10 => 
            array (
                'id' => 12,
                'parent_id' => 1,
                'order' => 4,
                'title' => '订单统计',
                'icon' => NULL,
                'url' => '/index/order',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:39:36',
                'updated_at' => '2023-05-11 23:27:16',
            ),
            11 => 
            array (
                'id' => 13,
                'parent_id' => 1,
                'order' => 5,
                'title' => '余额统计',
                'icon' => NULL,
                'url' => '/index/balance',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:40:06',
                'updated_at' => '2023-05-11 23:27:09',
            ),
            12 => 
            array (
                'id' => 14,
                'parent_id' => 0,
                'order' => 1,
                'title' => '用户',
                'icon' => 'material-symbols:person',
                'url' => '/user',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:55:27',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            13 => 
            array (
                'id' => 15,
                'parent_id' => 14,
                'order' => 0,
                'title' => '用户管理',
                'icon' => NULL,
                'url' => '/user/manage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:56:25',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            14 => 
            array (
                'id' => 16,
                'parent_id' => 0,
                'order' => 2,
                'title' => '订单',
                'icon' => 'ic:baseline-shopping-cart',
                'url' => '/order',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:58:49',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            15 => 
            array (
                'id' => 17,
                'parent_id' => 0,
                'order' => 3,
                'title' => '商品',
                'icon' => 'ep:goods',
                'url' => '/product',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 00:59:33',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            16 => 
            array (
                'id' => 18,
                'parent_id' => 0,
                'order' => 100,
                'title' => '维护',
                'icon' => 'streamline:interface-setting-hammer-construction-hammer-mallet-tool-tools-setting-edit-adjust',
                'url' => '/system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:01:07',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            17 => 
            array (
                'id' => 19,
                'parent_id' => 0,
                'order' => 5,
                'title' => '营销',
                'icon' => 'material-symbols:sell-sharp',
                'url' => '/market',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:02:07',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            18 => 
            array (
                'id' => 20,
                'parent_id' => 0,
                'order' => 6,
                'title' => '分销',
                'icon' => 'fluent:people-team-20-filled',
                'url' => '/agent',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:03:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            19 => 
            array (
                'id' => 21,
                'parent_id' => 0,
                'order' => 7,
                'title' => '客服',
                'icon' => 'material-symbols:sms',
                'url' => '/service',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:04:28',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            20 => 
            array (
                'id' => 22,
                'parent_id' => 0,
                'order' => 8,
                'title' => '财务',
                'icon' => 'material-symbols:attach-money',
                'url' => '/finance',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:05:16',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            21 => 
            array (
                'id' => 23,
                'parent_id' => 0,
                'order' => 9,
                'title' => '内容',
                'icon' => 'material-symbols:menu-book-outline',
                'url' => '/cms',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:06:10',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            22 => 
            array (
                'id' => 24,
                'parent_id' => 0,
                'order' => 10,
                'title' => '装修',
                'icon' => 'mdi:tools',
                'url' => '/page',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:06:58',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            23 => 
            array (
                'id' => 25,
                'parent_id' => 0,
                'order' => 11,
                'title' => '应用',
                'icon' => 'ic:outline-apple',
                'url' => '/app',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:08:17',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            24 => 
            array (
                'id' => 26,
                'parent_id' => 14,
                'order' => 1,
                'title' => '用户分组',
                'icon' => NULL,
                'url' => '/user/group',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:09:01',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            25 => 
            array (
                'id' => 27,
                'parent_id' => 14,
                'order' => 2,
                'title' => '用户标签',
                'icon' => NULL,
                'url' => '/user/label',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:09:27',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            26 => 
            array (
                'id' => 28,
                'parent_id' => 14,
                'order' => 3,
                'title' => '用户等级',
                'icon' => NULL,
                'url' => '/user/level',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:09:42',
                'updated_at' => '2023-05-14 23:18:21',
            ),
            27 => 
            array (
                'id' => 29,
                'parent_id' => 16,
                'order' => 0,
                'title' => '订单管理',
                'icon' => NULL,
                'url' => '/order/manage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:10:15',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            28 => 
            array (
                'id' => 30,
                'parent_id' => 16,
                'order' => 1,
                'title' => '售后订单',
                'icon' => NULL,
                'url' => '/order/after-sales',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:12:20',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            29 => 
            array (
                'id' => 31,
                'parent_id' => 16,
                'order' => 2,
                'title' => '核销订单',
                'icon' => NULL,
                'url' => '/order/verify',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:18:14',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            30 => 
            array (
                'id' => 32,
                'parent_id' => 16,
                'order' => 3,
                'title' => '收银订单',
                'icon' => NULL,
                'url' => '/order/offline',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:19:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            31 => 
            array (
                'id' => 33,
                'parent_id' => 17,
                'order' => 0,
                'title' => '商品管理',
                'icon' => NULL,
                'url' => '/product/manage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 01:19:34',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            32 => 
            array (
                'id' => 34,
                'parent_id' => 17,
                'order' => 1,
                'title' => '商品分类',
                'icon' => NULL,
                'url' => '/product/category',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:52:14',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            33 => 
            array (
                'id' => 35,
                'parent_id' => 17,
                'order' => 2,
                'title' => '商品规格',
                'icon' => NULL,
                'url' => '/product/attr',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:52:53',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            34 => 
            array (
                'id' => 36,
                'parent_id' => 17,
                'order' => 3,
                'title' => '商品评论',
                'icon' => NULL,
                'url' => '/product/comment',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:53:17',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            35 => 
            array (
                'id' => 37,
                'parent_id' => 19,
                'order' => 0,
                'title' => '优惠券',
                'icon' => NULL,
                'url' => '/market/coupon',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:54:11',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            36 => 
            array (
                'id' => 38,
                'parent_id' => 37,
                'order' => 0,
                'title' => '优惠券列表',
                'icon' => NULL,
                'url' => '/market/coupon/list',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:54:39',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            37 => 
            array (
                'id' => 39,
                'parent_id' => 37,
                'order' => 0,
                'title' => '用户领取记录',
                'icon' => NULL,
                'url' => '/market/coupon/get-record',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:55:31',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            38 => 
            array (
                'id' => 40,
                'parent_id' => 19,
                'order' => 1,
                'title' => '积分管理',
                'icon' => NULL,
                'url' => '/market/integral',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:57:03',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            39 => 
            array (
                'id' => 41,
                'parent_id' => 40,
                'order' => 0,
                'title' => '积分配置',
                'icon' => NULL,
                'url' => '/market/integral/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:57:32',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            40 => 
            array (
                'id' => 42,
                'parent_id' => 40,
                'order' => 1,
                'title' => '签到配置',
                'icon' => NULL,
                'url' => '/market/integral/sing',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:58:14',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            41 => 
            array (
                'id' => 43,
                'parent_id' => 40,
                'order' => 2,
                'title' => '积分商城',
                'icon' => NULL,
                'url' => '/market/integral/shop',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 08:59:16',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            42 => 
            array (
                'id' => 44,
                'parent_id' => 40,
                'order' => 3,
                'title' => '积分订单',
                'icon' => NULL,
                'url' => '/market/integral/order',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:00:04',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            43 => 
            array (
                'id' => 45,
                'parent_id' => 19,
                'order' => 2,
                'title' => '抽奖管理',
                'icon' => NULL,
                'url' => '/market/lottery',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:02:00',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            44 => 
            array (
                'id' => 46,
                'parent_id' => 19,
                'order' => 3,
                'title' => '砍价管理',
                'icon' => NULL,
                'url' => '/market/bargain',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:02:46',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            45 => 
            array (
                'id' => 47,
                'parent_id' => 46,
                'order' => 0,
                'title' => '砍价商品',
                'icon' => NULL,
                'url' => '/market/bargain/goods',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:03:27',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            46 => 
            array (
                'id' => 48,
                'parent_id' => 46,
                'order' => 1,
                'title' => '砍价列表',
                'icon' => NULL,
                'url' => '/market/bargain/list',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:03:50',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            47 => 
            array (
                'id' => 49,
                'parent_id' => 19,
                'order' => 4,
                'title' => '拼团管理',
                'icon' => NULL,
                'url' => '/market/combination',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:04:44',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            48 => 
            array (
                'id' => 50,
                'parent_id' => 49,
                'order' => 0,
                'title' => '拼团商品',
                'icon' => NULL,
                'url' => '/market/combination/goods',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:05:07',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            49 => 
            array (
                'id' => 51,
                'parent_id' => 49,
                'order' => 1,
                'title' => '拼团列表',
                'icon' => NULL,
                'url' => '/market/combination/list',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:05:27',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            50 => 
            array (
                'id' => 52,
                'parent_id' => 19,
                'order' => 5,
                'title' => '秒杀管理',
                'icon' => NULL,
                'url' => '/market/seckill',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:06:34',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            51 => 
            array (
                'id' => 53,
                'parent_id' => 52,
                'order' => 0,
                'title' => '秒杀商品',
                'icon' => NULL,
                'url' => '/market/seckill/goods',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:07:05',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            52 => 
            array (
                'id' => 54,
                'parent_id' => 52,
                'order' => 1,
                'title' => '秒杀配置',
                'icon' => NULL,
                'url' => '/market/seckill/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:07:26',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            53 => 
            array (
                'id' => 55,
                'parent_id' => 19,
                'order' => 6,
                'title' => '付费会员',
                'icon' => NULL,
                'url' => '/market/member',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:08:51',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            54 => 
            array (
                'id' => 56,
                'parent_id' => 19,
                'order' => 7,
                'title' => '直播管理',
                'icon' => NULL,
                'url' => '/market/live',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:09:28',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            55 => 
            array (
                'id' => 57,
                'parent_id' => 19,
                'order' => 8,
                'title' => '充值配置',
                'icon' => NULL,
                'url' => '/market/recharge',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:10:03',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            56 => 
            array (
                'id' => 58,
                'parent_id' => 19,
                'order' => 9,
                'title' => '渠道码',
                'icon' => NULL,
                'url' => '/market/channel-code',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:11:23',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            57 => 
            array (
                'id' => 59,
                'parent_id' => 56,
                'order' => 0,
                'title' => '直播间管理',
                'icon' => NULL,
                'url' => '/market/live/room',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:12:00',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            58 => 
            array (
                'id' => 60,
                'parent_id' => 56,
                'order' => 1,
                'title' => '直播商品管理',
                'icon' => NULL,
                'url' => '/market/live/goods',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:12:27',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            59 => 
            array (
                'id' => 61,
                'parent_id' => 56,
                'order' => 2,
                'title' => '主播配置',
                'icon' => NULL,
                'url' => '/market/live/anchor',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:13:00',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            60 => 
            array (
                'id' => 62,
                'parent_id' => 55,
                'order' => 0,
                'title' => '会员类型',
                'icon' => NULL,
                'url' => '/market/member/type',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:13:46',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            61 => 
            array (
                'id' => 63,
                'parent_id' => 55,
                'order' => 1,
                'title' => '会员权益',
                'icon' => NULL,
                'url' => '/market/member/benefit',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:15:12',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            62 => 
            array (
                'id' => 64,
                'parent_id' => 55,
                'order' => 2,
                'title' => '卡密会员',
                'icon' => NULL,
                'url' => '/market/member/card',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:15:47',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            63 => 
            array (
                'id' => 65,
                'parent_id' => 55,
                'order' => 3,
                'title' => '会员记录',
                'icon' => NULL,
                'url' => '/market/member/record',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:16:07',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            64 => 
            array (
                'id' => 66,
                'parent_id' => 21,
                'order' => 0,
                'title' => '客服列表',
                'icon' => NULL,
                'url' => '/service/list',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:17:06',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            65 => 
            array (
                'id' => 67,
                'parent_id' => 21,
                'order' => 1,
                'title' => '客服话术',
                'icon' => NULL,
                'url' => '/service/speechcraft',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:17:37',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            66 => 
            array (
                'id' => 68,
                'parent_id' => 21,
                'order' => 2,
                'title' => '用户留言',
                'icon' => NULL,
                'url' => '/service/feedback',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:18:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            67 => 
            array (
                'id' => 69,
                'parent_id' => 23,
                'order' => 0,
                'title' => '文章管理',
                'icon' => NULL,
                'url' => '/cms/article-manage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:18:59',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            68 => 
            array (
                'id' => 70,
                'parent_id' => 23,
                'order' => 1,
                'title' => '文章分类',
                'icon' => NULL,
                'url' => '/cms/article-category',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:19:29',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            69 => 
            array (
                'id' => 71,
                'parent_id' => 22,
                'order' => 0,
                'title' => '财务操作',
                'icon' => NULL,
                'url' => '/finance/transaction',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:22:16',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            70 => 
            array (
                'id' => 72,
                'parent_id' => 22,
                'order' => 1,
                'title' => '财务记录',
                'icon' => NULL,
                'url' => '/finance/record',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:22:47',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            71 => 
            array (
                'id' => 73,
                'parent_id' => 22,
                'order' => 2,
                'title' => '佣金记录',
                'icon' => NULL,
                'url' => '/finance/commission',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:23:21',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            72 => 
            array (
                'id' => 74,
                'parent_id' => 22,
                'order' => 3,
                'title' => '余额记录',
                'icon' => NULL,
                'url' => '/finance/balance',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:23:52',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            73 => 
            array (
                'id' => 75,
                'parent_id' => 71,
                'order' => 0,
                'title' => '提现申请',
                'icon' => NULL,
                'url' => '/finance/transaction/extract',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:24:37',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            74 => 
            array (
                'id' => 76,
                'parent_id' => 71,
                'order' => 1,
                'title' => '发票管理',
                'icon' => NULL,
                'url' => '/finance/transaction/invoice',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:25:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            75 => 
            array (
                'id' => 77,
                'parent_id' => 72,
                'order' => 0,
                'title' => '充值记录',
                'icon' => NULL,
                'url' => '/finance/record/recharge',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:28:15',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            76 => 
            array (
                'id' => 78,
                'parent_id' => 72,
                'order' => 1,
                'title' => '资金流水',
                'icon' => NULL,
                'url' => '/finance/record/capital',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:28:48',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            77 => 
            array (
                'id' => 79,
                'parent_id' => 72,
                'order' => 2,
                'title' => '账单记录',
                'icon' => NULL,
                'url' => '/finance/record/billing',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:29:36',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            78 => 
            array (
                'id' => 80,
                'parent_id' => 2,
                'order' => 0,
                'title' => '系统设置',
                'icon' => NULL,
                'url' => '/setting/system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:31:49',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            79 => 
            array (
                'id' => 81,
                'parent_id' => 80,
                'order' => 0,
                'title' => '基础配置',
                'icon' => NULL,
                'url' => '/setting/system/base',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:32:34',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            80 => 
            array (
                'id' => 82,
                'parent_id' => 80,
                'order' => 1,
                'title' => '商城',
                'icon' => NULL,
                'url' => '/setting/system/shop',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:32:59',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            81 => 
            array (
                'id' => 83,
                'parent_id' => 80,
                'order' => 2,
                'title' => '用户配置',
                'icon' => NULL,
                'url' => '/setting/system/user',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:33:23',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            82 => 
            array (
                'id' => 84,
                'parent_id' => 2,
                'order' => 1,
                'title' => '消息管理',
                'icon' => NULL,
                'url' => '/setting/notification',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:34:17',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            83 => 
            array (
                'id' => 85,
                'parent_id' => 84,
                'order' => 0,
                'title' => '通知会员',
                'icon' => NULL,
                'url' => '/setting/notification/member',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:34:58',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            84 => 
            array (
                'id' => 86,
                'parent_id' => 84,
                'order' => 1,
                'title' => '通知平台',
                'icon' => NULL,
                'url' => '/setting/notification/platform',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:35:56',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            85 => 
            array (
                'id' => 87,
                'parent_id' => 2,
                'order' => 3,
                'title' => '管理权限',
                'icon' => NULL,
                'url' => '/setting/admin',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 09:41:06',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            86 => 
            array (
                'id' => 89,
                'parent_id' => 20,
                'order' => 0,
                'title' => '分销员管理',
                'icon' => NULL,
                'url' => '/agent/user-manage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:46:08',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            87 => 
            array (
                'id' => 90,
                'parent_id' => 20,
                'order' => 1,
                'title' => '分销设置',
                'icon' => NULL,
                'url' => '/agent/setting',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:46:41',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            88 => 
            array (
                'id' => 91,
                'parent_id' => 20,
                'order' => 2,
                'title' => '分销等级',
                'icon' => NULL,
                'url' => '/agent/level',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:47:07',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            89 => 
            array (
                'id' => 92,
                'parent_id' => 20,
                'order' => 3,
                'title' => '事业部',
                'icon' => NULL,
                'url' => '/agent/division',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:48:04',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            90 => 
            array (
                'id' => 93,
                'parent_id' => 92,
                'order' => 0,
                'title' => '事业部列表',
                'icon' => NULL,
                'url' => '/agen/division/index',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:48:32',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            91 => 
            array (
                'id' => 94,
                'parent_id' => 92,
                'order' => 1,
                'title' => '代理商列表',
                'icon' => NULL,
                'url' => '/agent/division/agent',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:49:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            92 => 
            array (
                'id' => 95,
                'parent_id' => 92,
                'order' => 2,
                'title' => '代理商申请',
                'icon' => NULL,
                'url' => '/agent/division/apply',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:49:54',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            93 => 
            array (
                'id' => 96,
                'parent_id' => 24,
                'order' => 0,
                'title' => '页面设计',
                'icon' => NULL,
                'url' => '/page/devise',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:51:15',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            94 => 
            array (
                'id' => 97,
                'parent_id' => 24,
                'order' => 1,
                'title' => '数据配置',
                'icon' => NULL,
                'url' => '/page/data',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:51:48',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            95 => 
            array (
                'id' => 98,
                'parent_id' => 24,
                'order' => 2,
                'title' => '主题风格',
                'icon' => NULL,
                'url' => '/page/theme',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:52:13',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            96 => 
            array (
                'id' => 99,
                'parent_id' => 24,
                'order' => 3,
                'title' => 'PC商城',
                'icon' => NULL,
                'url' => '/page/pc',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:52:37',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            97 => 
            array (
                'id' => 100,
                'parent_id' => 24,
                'order' => 4,
                'title' => '素材管理',
                'icon' => NULL,
                'url' => '/page/file',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:53:03',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            98 => 
            array (
                'id' => 101,
                'parent_id' => 25,
                'order' => 0,
                'title' => '公众号',
                'icon' => NULL,
                'url' => '/app/wechat',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:54:01',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            99 => 
            array (
                'id' => 102,
                'parent_id' => 25,
                'order' => 1,
                'title' => '小程序',
                'icon' => NULL,
                'url' => '/app/mini-program',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:55:04',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            100 => 
            array (
                'id' => 103,
                'parent_id' => 25,
                'order' => 2,
                'title' => 'APP',
                'icon' => NULL,
                'url' => '/app/app',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:55:26',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            101 => 
            array (
                'id' => 104,
                'parent_id' => 25,
                'order' => 3,
                'title' => 'PC端',
                'icon' => NULL,
                'url' => '/app/pc',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:55:46',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            102 => 
            array (
                'id' => 105,
                'parent_id' => 101,
                'order' => 0,
                'title' => '微信菜单',
                'icon' => NULL,
                'url' => '/app/wechat/menu',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:56:21',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            103 => 
            array (
                'id' => 106,
                'parent_id' => 101,
                'order' => 1,
                'title' => '图文管理',
                'icon' => NULL,
                'url' => '/app/wechat/news',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:57:14',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            104 => 
            array (
                'id' => 107,
                'parent_id' => 101,
                'order' => 2,
                'title' => '自动回复',
                'icon' => NULL,
                'url' => '/app/wechat/reply',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:57:50',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            105 => 
            array (
                'id' => 108,
                'parent_id' => 107,
                'order' => 0,
                'title' => '关注回复',
                'icon' => NULL,
                'url' => '/app/wechat/reply/follow',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:58:54',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            106 => 
            array (
                'id' => 109,
                'parent_id' => 107,
                'order' => 1,
                'title' => '关键字回复',
                'icon' => NULL,
                'url' => '/app/wechat/reply/keyword',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-20 23:59:39',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            107 => 
            array (
                'id' => 110,
                'parent_id' => 107,
                'order' => 2,
                'title' => '无效词回复',
                'icon' => NULL,
                'url' => '/app/wechat/reply/default',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:00:15',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            108 => 
            array (
                'id' => 111,
                'parent_id' => 101,
                'order' => 3,
                'title' => '公众号配置',
                'icon' => NULL,
                'url' => '/app/wechat/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:00:56',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            109 => 
            array (
                'id' => 112,
                'parent_id' => 102,
                'order' => 0,
                'title' => '小程序下周',
                'icon' => NULL,
                'url' => '/app/min-program/download',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:01:34',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            110 => 
            array (
                'id' => 113,
                'parent_id' => 102,
                'order' => 1,
                'title' => '小程序配置',
                'icon' => NULL,
                'url' => '/app/mini-program/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:01:58',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            111 => 
            array (
                'id' => 114,
                'parent_id' => 103,
                'order' => 0,
                'title' => 'APP配置',
                'icon' => NULL,
                'url' => '/app/app/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:02:18',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            112 => 
            array (
                'id' => 115,
                'parent_id' => 103,
                'order' => 1,
                'title' => '版本管理',
                'icon' => NULL,
                'url' => '/app/app/version',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:02:40',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            113 => 
            array (
                'id' => 116,
                'parent_id' => 104,
                'order' => 0,
                'title' => 'PC端配置',
                'icon' => NULL,
                'url' => '/app/pc/configure',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:03:02',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            114 => 
            array (
                'id' => 117,
                'parent_id' => 2,
                'order' => 2,
                'title' => '协议设置',
                'icon' => NULL,
                'url' => '/setting/agreement',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:04:49',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            115 => 
            array (
                'id' => 118,
                'parent_id' => 2,
                'order' => 4,
                'title' => '发货设置',
                'icon' => NULL,
                'url' => '/setting/delivery',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:05:33',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            116 => 
            array (
                'id' => 119,
                'parent_id' => 118,
                'order' => 0,
                'title' => '配送员设置',
                'icon' => NULL,
                'url' => '/setting/delivery/user',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:06:09',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            117 => 
            array (
                'id' => 120,
                'parent_id' => 118,
                'order' => 1,
                'title' => '提货点设置',
                'icon' => NULL,
                'url' => '/setting/delivery/merchant',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:07:15',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            118 => 
            array (
                'id' => 121,
                'parent_id' => 120,
                'order' => 0,
                'title' => '提货点',
                'icon' => NULL,
                'url' => '/setting/delivery/merchant/list',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:08:26',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            119 => 
            array (
                'id' => 122,
                'parent_id' => 120,
                'order' => 1,
                'title' => '核销员',
                'icon' => NULL,
                'url' => '/setting/delivery/merchant/staff',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:10:01',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            120 => 
            array (
                'id' => 123,
                'parent_id' => 118,
                'order' => 2,
                'title' => '运费模板',
                'icon' => NULL,
                'url' => '/setting/delivery/template',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:11:46',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            121 => 
            array (
                'id' => 124,
                'parent_id' => 2,
                'order' => 5,
                'title' => '接口配置',
                'icon' => NULL,
                'url' => '/setting/interface',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:16:30',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            122 => 
            array (
                'id' => 125,
                'parent_id' => 124,
                'order' => 0,
                'title' => '一号通',
                'icon' => NULL,
                'url' => '/setting/interface/sms',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:17:01',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            123 => 
            array (
                'id' => 126,
                'parent_id' => 124,
                'order' => 1,
                'title' => '系统存储配置',
                'icon' => NULL,
                'url' => '/setting/interface/storage',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:17:44',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            124 => 
            array (
                'id' => 127,
                'parent_id' => 124,
                'order' => 2,
                'title' => '小票打印配置',
                'icon' => NULL,
                'url' => '/setting/interface/print',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:18:25',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            125 => 
            array (
                'id' => 128,
                'parent_id' => 124,
                'order' => 3,
                'title' => '商品采集配置',
                'icon' => NULL,
                'url' => '/setting/interface/copy',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:19:23',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            126 => 
            array (
                'id' => 129,
                'parent_id' => 124,
                'order' => 4,
                'title' => '物流查询配置',
                'icon' => NULL,
                'url' => '/setting/interface/logistics',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:20:06',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            127 => 
            array (
                'id' => 130,
                'parent_id' => 124,
                'order' => 5,
                'title' => '电子面单配置',
                'icon' => NULL,
                'url' => '/setting/interface/electronic',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:20:55',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            128 => 
            array (
                'id' => 131,
                'parent_id' => 124,
                'order' => 6,
                'title' => '短信接口配置',
                'icon' => NULL,
                'url' => '/setting/interface/sms2',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:21:35',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            129 => 
            array (
                'id' => 132,
                'parent_id' => 18,
                'order' => 0,
                'title' => '开发配置',
                'icon' => NULL,
                'url' => '/system/develop',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:22:39',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            130 => 
            array (
                'id' => 133,
                'parent_id' => 132,
                'order' => 3,
                'title' => '定时任务',
                'icon' => NULL,
                'url' => '/system/develop/crontab',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:23:20',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            131 => 
            array (
                'id' => 134,
                'parent_id' => 132,
                'order' => 0,
                'title' => '配置分类',
                'icon' => NULL,
                'url' => '/system/develop/config-tab',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:24:05',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            132 => 
            array (
                'id' => 135,
                'parent_id' => 132,
                'order' => 1,
                'title' => '组合数据',
                'icon' => NULL,
                'url' => '/system/develop/group-data',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:24:49',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            133 => 
            array (
                'id' => 136,
                'parent_id' => 132,
                'order' => 2,
                'title' => '文件管理',
                'icon' => NULL,
                'url' => '/system/develop/file-system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:25:22',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            134 => 
            array (
                'id' => 137,
                'parent_id' => 18,
                'order' => 1,
                'title' => '安全维护',
                'icon' => NULL,
                'url' => '/system/maintain',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:26:00',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            135 => 
            array (
                'id' => 138,
                'parent_id' => 137,
                'order' => 0,
                'title' => '刷新缓存',
                'icon' => NULL,
                'url' => '/system/maintain/cache',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:26:28',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            136 => 
            array (
                'id' => 139,
                'parent_id' => 137,
                'order' => 1,
                'title' => '系统日志',
                'icon' => NULL,
                'url' => '/system/maintain/log',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:26:54',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            137 => 
            array (
                'id' => 140,
                'parent_id' => 137,
                'order' => 2,
                'title' => '文件校验',
                'icon' => NULL,
                'url' => '/system/maintain/file-verify',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:27:49',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            138 => 
            array (
                'id' => 141,
                'parent_id' => 18,
                'order' => 2,
                'title' => '数据维护',
                'icon' => NULL,
                'url' => '/system/data',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:28:31',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            139 => 
            array (
                'id' => 142,
                'parent_id' => 141,
                'order' => 0,
                'title' => '物流公司',
                'icon' => NULL,
                'url' => '/system/data/express',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:29:02',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            140 => 
            array (
                'id' => 143,
                'parent_id' => 141,
                'order' => 1,
                'title' => '城市数据',
                'icon' => NULL,
                'url' => '/system/data/city',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:29:37',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            141 => 
            array (
                'id' => 144,
                'parent_id' => 141,
                'order' => 2,
                'title' => '数据备份',
                'icon' => NULL,
                'url' => '/system/data/backup',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:30:02',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            142 => 
            array (
                'id' => 145,
                'parent_id' => 18,
                'order' => 3,
                'title' => '系统对外接口',
                'icon' => NULL,
                'url' => '/system/extract',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:30:47',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            143 => 
            array (
                'id' => 146,
                'parent_id' => 145,
                'order' => 0,
                'title' => '账号管理',
                'icon' => NULL,
                'url' => '/system/extract/account',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:31:20',
                'updated_at' => '2023-05-11 23:26:37',
            ),
            144 => 
            array (
                'id' => 147,
                'parent_id' => 145,
                'order' => 1,
                'title' => '接口文档',
                'icon' => NULL,
                'url' => '/system/extract/document',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'extension' => NULL,
                'created_at' => '2023-04-21 00:31:50',
                'updated_at' => '2023-05-11 23:26:37',
            ),
        ));
        
        
    }
}